# Generated by Django 3.2.10 on 2022-12-14 18:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('question', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('raw', 'Необработанный'), ('finished', 'Обработанный')], db_index=True, default='raw', max_length=25, verbose_name='Статус звонка')),
            ],
            options={
                'verbose_name': 'Консультация пользователя',
                'verbose_name_plural': 'Консультация пользователей',
            },
        ),
    ]
