# Generated by Django 3.2.10 on 2022-12-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221214_2348'),
        ('users', '0003_auto_20221215_1148'),
    ]

    operations = [
    ]
