# Generated by Django 3.2.10 on 2022-12-20 07:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=80, verbose_name='Фамилия')),
                ('avatar', models.FileField(null=True, upload_to='media/', verbose_name='аватар')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='beauty.category', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon_name', models.CharField(max_length=50, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Адрес')),
                ('image', models.FileField(null=True, upload_to='media/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Салон',
                'verbose_name_plural': 'Салоны',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('image', models.FileField(null=True, upload_to='media/', verbose_name='картинка')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='procedure', to='beauty.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Процедура',
                'verbose_name_plural': 'Процедуры',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField(verbose_name='Текст')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='beauty.employee', verbose_name='Мастер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='salon',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='masters', to='beauty.salon', verbose_name='Салон'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(blank=True, choices=[('Mo', 'Пн'), ('Tu', 'Вт'), ('We', 'Ср'), ('Td', 'Чт'), ('Fr', 'Пт'), ('Sa', 'Сб'), ('Su', 'Вс')], max_length=20, verbose_name='Рабочие дни')),
                ('appointment_hour', models.CharField(blank=True, choices=[('9:00 - 10:00', '9:00'), ('10:00 - 11:00', '10:00'), ('11:00 - 12:00', '11:00'), ('12:00 - 13:00', '12:00'), ('13:00 - 14:00', '13:00'), ('14:00 - 15:00', '14:00'), ('15:00 - 16:00', '15:00'), ('16:00 - 17:00', '16:00'), ('17:00 - 18:00', '17:00'), ('18:00 - 19:00', '18:00'), ('19:00 - 20:00', '19:00'), ('20:00 - 21:00', '20:00')], max_length=15, verbose_name='Время записи')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='beauty.employee', verbose_name='Мастер')),
                ('procedure', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='beauty.procedure', verbose_name='Процедура')),
                ('salons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='beauty.salon')),
            ],
            options={
                'verbose_name': 'Приём',
                'verbose_name_plural': 'Приёмы',
                'unique_together': {('day_of_week', 'appointment_hour')},
            },
        ),
    ]
