# Generated by Django 3.2.10 on 2022-12-15 17:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(blank=True, choices=[('Mo', 'Пн'), ('Tu', 'Вт'), ('We', 'Ср'), ('Td', 'Чт'), ('Fr', 'Пт'), ('Sa', 'Сб'), ('Su', 'Вс')], max_length=20, verbose_name='Рабочие дни')),
                ('appointment_hour', models.CharField(blank=True, choices=[('9:00 - 10:00', '9:00'), ('10:00 - 11:00', '10:00'), ('11:00 - 12:00', '11:00'), ('12:00 - 13:00', '12:00'), ('13:00 - 14:00', '13:00'), ('14:00 - 15:00', '14:00'), ('15:00 - 16:00', '15:00'), ('16:00 - 17:00', '16:00'), ('17:00 - 18:00', '17:00'), ('18:00 - 19:00', '18:00'), ('19:00 - 20:00', '19:00'), ('20:00 - 21:00', '20:00')], max_length=15, verbose_name='Время записи')),
            ],
            options={
                'verbose_name': 'Приём',
                'verbose_name_plural': 'Приёмы',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Категория')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=80, verbose_name='Фамилия')),
                ('avatar', models.ImageField(null=True, upload_to='', verbose_name='аватар')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'Процедура',
                'verbose_name_plural': 'Процедуры',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon_name', models.CharField(max_length=50, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Адрес')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Картинка')),
                ('employees', models.ManyToManyField(related_name='salons', through='beauty.Appointment', to='beauty.Employee')),
                ('procedure_categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salons', to='beauty.category')),
            ],
            options={
                'verbose_name': 'Салон',
                'verbose_name_plural': 'Салоны',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='beauty.order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='beauty.appointment')),
            ],
            options={
                'verbose_name': 'Атрибуты заказа',
                'verbose_name_plural': 'Атрибуты ',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='procedures',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masters', to='beauty.procedure'),
        ),
        migrations.AddField(
            model_name='category',
            name='procedures',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='beauty.procedure'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='employees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='beauty.employee'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='salons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='beauty.salon'),
        ),
    ]
