# Generated by Django 3.2.10 on 2022-12-15 21:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beauty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='procedures',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='procedures',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='procedure_categories',
        ),
        migrations.AddField(
            model_name='employee',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='beauty.category', verbose_name='Специальность'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='procedure', to='beauty.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.FileField(null=True, upload_to='media/', verbose_name='аватар'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='image',
            field=models.FileField(null=True, upload_to='media/', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='image',
            field=models.FileField(null=True, upload_to='media/', verbose_name='Картинка'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField(verbose_name='Текст')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='beauty.employee', verbose_name='Мастер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
