# Generated by Django 3.2.10 on 2022-12-15 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Приём', 'verbose_name_plural': 'Приёмы'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
        migrations.AlterModelOptions(
            name='procedure',
            options={'verbose_name': 'Процедура', 'verbose_name_plural': 'Процедуры'},
        ),
        migrations.AlterModelOptions(
            name='salon',
            options={'verbose_name': 'Салон', 'verbose_name_plural': 'Салоны'},
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Категория')),
                ('procedures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='beauty.procedure')),
            ],
        ),
        migrations.AddField(
            model_name='salon',
            name='procedure_categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salons', to='beauty.category'),
        ),
    ]
