# Generated by Django 3.2.10 on 2022-12-17 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0002_auto_20221215_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='employees',
        ),
        migrations.AddField(
            model_name='employee',
            name='salon',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='beauty.salon', verbose_name='Салон'),
        ),
    ]
