# Generated by Django 3.2.10 on 2022-12-20 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0002_auto_20221220_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='employees',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='salons',
            new_name='salon',
        ),
        migrations.RenameField(
            model_name='salon',
            old_name='salon_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salon',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='DayOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(blank=True, choices=[('Mo', 'Пн'), ('Tu', 'Вт'), ('We', 'Ср'), ('Td', 'Чт'), ('Fr', 'Пт'), ('Sa', 'Сб'), ('Su', 'Вс')], max_length=20, verbose_name='Рабочие дни')),
                ('ready', models.BooleanField(default=False)),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_of_works', to='beauty.employee', verbose_name='Мастер')),
                ('salons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_of_works', to='beauty.salon')),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='salon',
            name='employee',
            field=models.ManyToManyField(through='beauty.DayOfWork', to='beauty.Employee'),
        ),
    ]
