# Generated by Django 3.2.10 on 2022-12-20 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0003_auto_20221220_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='beauty.category', verbose_name='Категории'),
        ),
    ]
