# Generated by Django 3.2.10 on 2022-12-17 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0004_alter_employee_salon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masters', to='beauty.salon', verbose_name='Салон'),
        ),
    ]
