# Generated by Django 3.2.10 on 2022-12-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0004_alter_procedure_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_hour',
            field=models.CharField(blank=True, choices=[('9:00', '9:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00')], max_length=15, verbose_name='Время записи'),
        ),
    ]
