# Generated by Django 3.2.10 on 2022-12-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='картинка'),
        ),
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(null=True, upload_to='', verbose_name='аватар'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='картинка'),
        ),
        migrations.AddField(
            model_name='salon',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Картинка'),
        ),
    ]
